name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 2.1.1
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.18
  uuid:  ^3.0.0-nullsafety.0
  http: ^0.13.0-nullsafety.0
  path: ^1.8.0
  sqflite: ^2.0.0-nullsafety.3
  pedantic: ^1.8.0+1
  clock: ^1.0.1
  file: ^6.0.0
  rxdart: 0.26.0-nullsafety.1
  image: ^2.1.18
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
